package model.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import model.eo.TIME_CARD_DTL_EOImpl;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Feb 23 19:18:55 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XXSC_TIME_CARD_DTL_VORowImpl extends ViewRowImpl {


    public static final int ENTITY_TIME_CARD_DTL_EO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ActiveFlag,
        CreatedBy,
        CreationDate,
        EmployeeId,
        EmployeeName,
        EmployeeNumber,
        IncentiveHrs,
        IncentiveRate,
        IncentiveUnitRate,
        JobTypeCode,
        JobTypeName,
        JobTypeRate,
        LastUpdateDate,
        LastUpdateLogin,
        LastUpdatedBy,
        OverTimeHrs,
        OverTimeRate,
        OverTimeUnitRate,
        PayrollFlag,
        RegularHrs,
        RegularRate,
        RegularUnitRate,
        Status,
        TaskId,
        TaskName,
        TaskNumber,
        TimeCardDtlId,
        TimeCardMasterId,
        RejectReason,
        TotalAmount,
        TimeCardDate;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ACTIVEFLAG = AttributesEnum.ActiveFlag.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int EMPLOYEEID = AttributesEnum.EmployeeId.index();
    public static final int EMPLOYEENAME = AttributesEnum.EmployeeName.index();
    public static final int EMPLOYEENUMBER = AttributesEnum.EmployeeNumber.index();
    public static final int INCENTIVEHRS = AttributesEnum.IncentiveHrs.index();
    public static final int INCENTIVERATE = AttributesEnum.IncentiveRate.index();
    public static final int INCENTIVEUNITRATE = AttributesEnum.IncentiveUnitRate.index();
    public static final int JOBTYPECODE = AttributesEnum.JobTypeCode.index();
    public static final int JOBTYPENAME = AttributesEnum.JobTypeName.index();
    public static final int JOBTYPERATE = AttributesEnum.JobTypeRate.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int OVERTIMEHRS = AttributesEnum.OverTimeHrs.index();
    public static final int OVERTIMERATE = AttributesEnum.OverTimeRate.index();
    public static final int OVERTIMEUNITRATE = AttributesEnum.OverTimeUnitRate.index();
    public static final int PAYROLLFLAG = AttributesEnum.PayrollFlag.index();
    public static final int REGULARHRS = AttributesEnum.RegularHrs.index();
    public static final int REGULARRATE = AttributesEnum.RegularRate.index();
    public static final int REGULARUNITRATE = AttributesEnum.RegularUnitRate.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int TASKID = AttributesEnum.TaskId.index();
    public static final int TASKNAME = AttributesEnum.TaskName.index();
    public static final int TASKNUMBER = AttributesEnum.TaskNumber.index();
    public static final int TIMECARDDTLID = AttributesEnum.TimeCardDtlId.index();
    public static final int TIMECARDMASTERID = AttributesEnum.TimeCardMasterId.index();
    public static final int REJECTREASON = AttributesEnum.RejectReason.index();
    public static final int TOTALAMOUNT = AttributesEnum.TotalAmount.index();
    public static final int TIMECARDDATE = AttributesEnum.TimeCardDate.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XXSC_TIME_CARD_DTL_VORowImpl() {
    }

    /**
     * Gets TIME_CARD_DTL_EO entity object.
     * @return the TIME_CARD_DTL_EO
     */
    public TIME_CARD_DTL_EOImpl getTIME_CARD_DTL_EO() {
        return (TIME_CARD_DTL_EOImpl) getEntity(ENTITY_TIME_CARD_DTL_EO);
    }

    /**
     * Gets the attribute value for ACTIVE_FLAG using the alias name ActiveFlag.
     * @return the ACTIVE_FLAG
     */
    public String getActiveFlag() {
        return (String) getAttributeInternal(ACTIVEFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTIVE_FLAG using the alias name ActiveFlag.
     * @param value value to set the ACTIVE_FLAG
     */
    public void setActiveFlag(String value) {
        setAttributeInternal(ACTIVEFLAG, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for EMPLOYEE_ID using the alias name EmployeeId.
     * @return the EMPLOYEE_ID
     */
    public BigDecimal getEmployeeId() {
        return (BigDecimal) getAttributeInternal(EMPLOYEEID);
    }

    /**
     * Sets <code>value</code> as attribute value for EMPLOYEE_ID using the alias name EmployeeId.
     * @param value value to set the EMPLOYEE_ID
     */
    public void setEmployeeId(BigDecimal value) {
        setAttributeInternal(EMPLOYEEID, value);
    }

    /**
     * Gets the attribute value for EMPLOYEE_NAME using the alias name EmployeeName.
     * @return the EMPLOYEE_NAME
     */
    public String getEmployeeName() {
        return (String) getAttributeInternal(EMPLOYEENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for EMPLOYEE_NAME using the alias name EmployeeName.
     * @param value value to set the EMPLOYEE_NAME
     */
    public void setEmployeeName(String value) {
        setAttributeInternal(EMPLOYEENAME, value);
    }

    /**
     * Gets the attribute value for EMPLOYEE_NUMBER using the alias name EmployeeNumber.
     * @return the EMPLOYEE_NUMBER
     */
    public String getEmployeeNumber() {
        return (String) getAttributeInternal(EMPLOYEENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for EMPLOYEE_NUMBER using the alias name EmployeeNumber.
     * @param value value to set the EMPLOYEE_NUMBER
     */
    public void setEmployeeNumber(String value) {
        setAttributeInternal(EMPLOYEENUMBER, value);
    }

    /**
     * Gets the attribute value for INCENTIVE_HRS using the alias name IncentiveHrs.
     * @return the INCENTIVE_HRS
     */
    public BigDecimal getIncentiveHrs() {
        return (BigDecimal) getAttributeInternal(INCENTIVEHRS);
    }

    /**
     * Sets <code>value</code> as attribute value for INCENTIVE_HRS using the alias name IncentiveHrs.
     * @param value value to set the INCENTIVE_HRS
     */
    public void setIncentiveHrs(BigDecimal value) {
        setAttributeInternal(INCENTIVEHRS, value);
    }

    /**
     * Gets the attribute value for INCENTIVE_RATE using the alias name IncentiveRate.
     * @return the INCENTIVE_RATE
     */
    public BigDecimal getIncentiveRate() {
        return (BigDecimal) getAttributeInternal(INCENTIVERATE);
    }

    /**
     * Sets <code>value</code> as attribute value for INCENTIVE_RATE using the alias name IncentiveRate.
     * @param value value to set the INCENTIVE_RATE
     */
    public void setIncentiveRate(BigDecimal value) {
        setAttributeInternal(INCENTIVERATE, value);
    }

    /**
     * Gets the attribute value for INCENTIVE_UNIT_RATE using the alias name IncentiveUnitRate.
     * @return the INCENTIVE_UNIT_RATE
     */
    public BigDecimal getIncentiveUnitRate() {
        return (BigDecimal) getAttributeInternal(INCENTIVEUNITRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for INCENTIVE_UNIT_RATE using the alias name IncentiveUnitRate.
     * @param value value to set the INCENTIVE_UNIT_RATE
     */
    public void setIncentiveUnitRate(BigDecimal value) {
        setAttributeInternal(INCENTIVEUNITRATE, value);
    }

    /**
     * Gets the attribute value for JOB_TYPE_CODE using the alias name JobTypeCode.
     * @return the JOB_TYPE_CODE
     */
    public String getJobTypeCode() {
        return (String) getAttributeInternal(JOBTYPECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for JOB_TYPE_CODE using the alias name JobTypeCode.
     * @param value value to set the JOB_TYPE_CODE
     */
    public void setJobTypeCode(String value) {
        setAttributeInternal(JOBTYPECODE, value);
    }

    /**
     * Gets the attribute value for JOB_TYPE_NAME using the alias name JobTypeName.
     * @return the JOB_TYPE_NAME
     */
    public String getJobTypeName() {
        return (String) getAttributeInternal(JOBTYPENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for JOB_TYPE_NAME using the alias name JobTypeName.
     * @param value value to set the JOB_TYPE_NAME
     */
    public void setJobTypeName(String value) {
        setAttributeInternal(JOBTYPENAME, value);
    }

    /**
     * Gets the attribute value for JOB_TYPE_RATE using the alias name JobTypeRate.
     * @return the JOB_TYPE_RATE
     */
    public BigDecimal getJobTypeRate() {
        return (BigDecimal) getAttributeInternal(JOBTYPERATE);
    }

    /**
     * Sets <code>value</code> as attribute value for JOB_TYPE_RATE using the alias name JobTypeRate.
     * @param value value to set the JOB_TYPE_RATE
     */
    public void setJobTypeRate(BigDecimal value) {
        setAttributeInternal(JOBTYPERATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Gets the attribute value for OVER_TIME_HRS using the alias name OverTimeHrs.
     * @return the OVER_TIME_HRS
     */
    public BigDecimal getOverTimeHrs() {
        return (BigDecimal) getAttributeInternal(OVERTIMEHRS);
    }

    /**
     * Sets <code>value</code> as attribute value for OVER_TIME_HRS using the alias name OverTimeHrs.
     * @param value value to set the OVER_TIME_HRS
     */
    public void setOverTimeHrs(BigDecimal value) {
        setAttributeInternal(OVERTIMEHRS, value);
    }

    /**
     * Gets the attribute value for OVER_TIME_RATE using the alias name OverTimeRate.
     * @return the OVER_TIME_RATE
     */
    public BigDecimal getOverTimeRate() {
        return (BigDecimal) getAttributeInternal(OVERTIMERATE);
    }

    /**
     * Sets <code>value</code> as attribute value for OVER_TIME_RATE using the alias name OverTimeRate.
     * @param value value to set the OVER_TIME_RATE
     */
    public void setOverTimeRate(BigDecimal value) {
        setAttributeInternal(OVERTIMERATE, value);
    }

    /**
     * Gets the attribute value for OVER_TIME_UNIT_RATE using the alias name OverTimeUnitRate.
     * @return the OVER_TIME_UNIT_RATE
     */
    public BigDecimal getOverTimeUnitRate() {
        return (BigDecimal) getAttributeInternal(OVERTIMEUNITRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for OVER_TIME_UNIT_RATE using the alias name OverTimeUnitRate.
     * @param value value to set the OVER_TIME_UNIT_RATE
     */
    public void setOverTimeUnitRate(BigDecimal value) {
        setAttributeInternal(OVERTIMEUNITRATE, value);
    }

    /**
     * Gets the attribute value for PAYROLL_FLAG using the alias name PayrollFlag.
     * @return the PAYROLL_FLAG
     */
    public String getPayrollFlag() {
        return (String) getAttributeInternal(PAYROLLFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYROLL_FLAG using the alias name PayrollFlag.
     * @param value value to set the PAYROLL_FLAG
     */
    public void setPayrollFlag(String value) {
        setAttributeInternal(PAYROLLFLAG, value);
    }

    /**
     * Gets the attribute value for REGULAR_HRS using the alias name RegularHrs.
     * @return the REGULAR_HRS
     */
    public BigDecimal getRegularHrs() {
        return (BigDecimal) getAttributeInternal(REGULARHRS);
    }

    /**
     * Sets <code>value</code> as attribute value for REGULAR_HRS using the alias name RegularHrs.
     * @param value value to set the REGULAR_HRS
     */
    public void setRegularHrs(BigDecimal value) {
        setAttributeInternal(REGULARHRS, value);
    }

    /**
     * Gets the attribute value for REGULAR_RATE using the alias name RegularRate.
     * @return the REGULAR_RATE
     */
    public BigDecimal getRegularRate() {
        return (BigDecimal) getAttributeInternal(REGULARRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for REGULAR_RATE using the alias name RegularRate.
     * @param value value to set the REGULAR_RATE
     */
    public void setRegularRate(BigDecimal value) {
        setAttributeInternal(REGULARRATE, value);
    }

    /**
     * Gets the attribute value for REGULAR_UNIT_RATE using the alias name RegularUnitRate.
     * @return the REGULAR_UNIT_RATE
     */
    public BigDecimal getRegularUnitRate() {
        return (BigDecimal) getAttributeInternal(REGULARUNITRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for REGULAR_UNIT_RATE using the alias name RegularUnitRate.
     * @param value value to set the REGULAR_UNIT_RATE
     */
    public void setRegularUnitRate(BigDecimal value) {
        setAttributeInternal(REGULARUNITRATE, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for TASK_ID using the alias name TaskId.
     * @return the TASK_ID
     */
    public BigDecimal getTaskId() {
        return (BigDecimal) getAttributeInternal(TASKID);
    }

    /**
     * Sets <code>value</code> as attribute value for TASK_ID using the alias name TaskId.
     * @param value value to set the TASK_ID
     */
    public void setTaskId(BigDecimal value) {
        setAttributeInternal(TASKID, value);
    }

    /**
     * Gets the attribute value for TASK_NAME using the alias name TaskName.
     * @return the TASK_NAME
     */
    public String getTaskName() {
        return (String) getAttributeInternal(TASKNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TASK_NAME using the alias name TaskName.
     * @param value value to set the TASK_NAME
     */
    public void setTaskName(String value) {
        setAttributeInternal(TASKNAME, value);
    }

    /**
     * Gets the attribute value for TASK_NUMBER using the alias name TaskNumber.
     * @return the TASK_NUMBER
     */
    public String getTaskNumber() {
        return (String) getAttributeInternal(TASKNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for TASK_NUMBER using the alias name TaskNumber.
     * @param value value to set the TASK_NUMBER
     */
    public void setTaskNumber(String value) {
        setAttributeInternal(TASKNUMBER, value);
    }

    /**
     * Gets the attribute value for TIME_CARD_DTL_ID using the alias name TimeCardDtlId.
     * @return the TIME_CARD_DTL_ID
     */
    public BigDecimal getTimeCardDtlId() {
        return (BigDecimal) getAttributeInternal(TIMECARDDTLID);
    }

    /**
     * Sets <code>value</code> as attribute value for TIME_CARD_DTL_ID using the alias name TimeCardDtlId.
     * @param value value to set the TIME_CARD_DTL_ID
     */
    public void setTimeCardDtlId(BigDecimal value) {
        setAttributeInternal(TIMECARDDTLID, value);
    }

    /**
     * Gets the attribute value for TIME_CARD_MASTER_ID using the alias name TimeCardMasterId.
     * @return the TIME_CARD_MASTER_ID
     */
    public BigDecimal getTimeCardMasterId() {
        return (BigDecimal) getAttributeInternal(TIMECARDMASTERID);
    }

    /**
     * Sets <code>value</code> as attribute value for TIME_CARD_MASTER_ID using the alias name TimeCardMasterId.
     * @param value value to set the TIME_CARD_MASTER_ID
     */
    public void setTimeCardMasterId(BigDecimal value) {
        setAttributeInternal(TIMECARDMASTERID, value);
    }

    /**
     * Gets the attribute value for REJECT_REASON using the alias name RejectReason.
     * @return the REJECT_REASON
     */
    public String getRejectReason() {
        return (String) getAttributeInternal(REJECTREASON);
    }

    /**
     * Sets <code>value</code> as attribute value for REJECT_REASON using the alias name RejectReason.
     * @param value value to set the REJECT_REASON
     */
    public void setRejectReason(String value) {
        setAttributeInternal(REJECTREASON, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TimeCardDate.
     * @return the TimeCardDate
     */
    public Timestamp getTimeCardDate() {
        return (Timestamp) getAttributeInternal(TIMECARDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TimeCardDate.
     * @param value value to set the  TimeCardDate
     */
    public void setTimeCardDate(Timestamp value) {
        setAttributeInternal(TIMECARDDATE, value);
    }

    /**
     * Gets the attribute value for TOTAL_AMOUNT using the alias name TotalAmount.
     * @return the TOTAL_AMOUNT
     */
    public BigDecimal getTotalAmount() {
        return (BigDecimal) getAttributeInternal(TOTALAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_AMOUNT using the alias name TotalAmount.
     * @param value value to set the TOTAL_AMOUNT
     */
    public void setTotalAmount(BigDecimal value) {
        setAttributeInternal(TOTALAMOUNT, value);
    }
}

