package model.rovo;

import java.math.BigDecimal;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jan 15 18:55:12 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NextApprover_ROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public NextApprover_ROVOImpl() {
    }
}

