package model.vo;

import java.sql.Timestamp;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Feb 08 19:21:44 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XXSC_TIME_CARD_DTL_VOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public XXSC_TIME_CARD_DTL_VOImpl() {
    }

    /**
     * Returns the variable value for BV_EMP_NUM.
     * @return variable value for BV_EMP_NUM
     */
    public String getBV_EMP_NUM() {
        return (String) ensureVariableManager().getVariableValue("BV_EMP_NUM");
    }

    /**
     * Sets <code>value</code> for variable BV_EMP_NUM.
     * @param value value to bind as BV_EMP_NUM
     */
    public void setBV_EMP_NUM(String value) {
        ensureVariableManager().setVariableValue("BV_EMP_NUM", value);
    }

    /**
     * Returns the variable value for BV_Date.
     * @return variable value for BV_Date
     */
    public Timestamp getBV_Date() {
        return (Timestamp) ensureVariableManager().getVariableValue("BV_Date");
    }

    /**
     * Sets <code>value</code> for variable BV_Date.
     * @param value value to bind as BV_Date
     */
    public void setBV_Date(Timestamp value) {
        ensureVariableManager().setVariableValue("BV_Date", value);
    }
}

