package model.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 12 18:34:01 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TIME_CARD_MASTER_VOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public TIME_CARD_MASTER_VOImpl() {
    }

    /**
     * Returns the variable value for p_Id.
     * @return variable value for p_Id
     */
    public BigDecimal getp_Id() {
        return (BigDecimal) ensureVariableManager().getVariableValue("p_Id");
    }

    /**
     * Sets <code>value</code> for variable p_Id.
     * @param value value to bind as p_Id
     */
    public void setp_Id(BigDecimal value) {
        ensureVariableManager().setVariableValue("p_Id", value);
    }

    /**
     * Returns the bind variable value for BV_USER_NAME.
     * @return bind variable value for BV_USER_NAME
     */
    public String getBV_USER_NAME() {
        return (String) getNamedWhereClauseParam("BV_USER_NAME");
    }

    /**
     * Sets <code>value</code> for bind variable BV_USER_NAME.
     * @param value value to bind as BV_USER_NAME
     */
    public void setBV_USER_NAME(String value) {
        setNamedWhereClauseParam("BV_USER_NAME", value);
    }

    /**
     * Returns the variable value for BV_date.
     * @return variable value for BV_date
     */
    public Timestamp getBV_date() {
        return (Timestamp) ensureVariableManager().getVariableValue("BV_date");
    }

    /**
     * Sets <code>value</code> for variable BV_date.
     * @param value value to bind as BV_date
     */
    public void setBV_date(Timestamp value) {
        ensureVariableManager().setVariableValue("BV_date", value);
    }

    /**
     * Returns the variable value for BV_code.
     * @return variable value for BV_code
     */
    public String getBV_code() {
        return (String) ensureVariableManager().getVariableValue("BV_code");
    }

    /**
     * Sets <code>value</code> for variable BV_code.
     * @param value value to bind as BV_code
     */
    public void setBV_code(String value) {
        ensureVariableManager().setVariableValue("BV_code", value);
    }

    /**
     * Returns the variable value for BV_Project.
     * @return variable value for BV_Project
     */
    public BigDecimal getBV_Project() {
        return (BigDecimal) ensureVariableManager().getVariableValue("BV_Project");
    }

    /**
     * Sets <code>value</code> for variable BV_Project.
     * @param value value to bind as BV_Project
     */
    public void setBV_Project(BigDecimal value) {
        ensureVariableManager().setVariableValue("BV_Project", value);
    }

    /**
     * Returns the bind variable value for BV_FILTER_USER.
     * @return bind variable value for BV_FILTER_USER
     */
    public String getBV_FILTER_USER() {
        return (String) getNamedWhereClauseParam("BV_FILTER_USER");
    }

    /**
     * Sets <code>value</code> for bind variable BV_FILTER_USER.
     * @param value value to bind as BV_FILTER_USER
     */
    public void setBV_FILTER_USER(String value) {
        setNamedWhereClauseParam("BV_FILTER_USER", value);
    }

    /**
     * Returns the variable value for BV_NEXT_Approver.
     * @return variable value for BV_NEXT_Approver
     */
    public String getBV_NEXT_Approver() {
        return (String) ensureVariableManager().getVariableValue("BV_NEXT_Approver");
    }

    /**
     * Sets <code>value</code> for variable BV_NEXT_Approver.
     * @param value value to bind as BV_NEXT_Approver
     */
    public void setBV_NEXT_Approver(String value) {
        ensureVariableManager().setVariableValue("BV_NEXT_Approver", value);
    }
}

