package model.rovo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Feb 21 15:32:12 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UserRole_ROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public UserRole_ROVOImpl() {
    }
}

