package model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Feb 21 16:35:34 IST 2020
// ---------------------------------------------------------------------
public interface Naresco_AM extends ApplicationModule {
    void dataFilter();
}

