package model.rovo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Dec 22 16:55:57 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Jobs_ROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public Jobs_ROVOImpl() {
    }
}

