package model.rovo;

import java.math.BigDecimal;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 24 09:52:09 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class JobType_ROVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public JobType_ROVOImpl() {
    }
}

